name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: v19.1.0

    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run ESLint
      run: npm run lint